name: wishlist_net

services:
  mongodb:
    image: mongo:6.0
    container_name: wishlist_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - wishlist_net

  redis:
    image: redis:7-alpine
    container_name: wishlist_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wishlist_net

  neo4j:
    image: neo4j:5
    container_name: wishlist_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testpassword123
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - wishlist_net

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: wishlist_redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    networks:
      - wishlist_net

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH=false
    ports:
      - "8091:8081"
    networks:
      - wishlist_net

volumes:
  mongo_data:
  redis_data:
  neo4j_data:
  neo4j_logs:
  redisinsight_data:

networks:
  wishlist_net:
    driver: bridge
